[build-system]
requires = [
  "wheel",
  "setuptools>=45",
  "setuptools_scm[toml]>=6.0",
  "pybind11>=2.6",
]

[tool.setuptools_scm]
write_to = "src/iqrm/_version.py"

[project]
authors = [
  {name = "Vincent Morello", email = "vmorello@gmail.com"},
]
dynamic = ["version"]
classifiers = [
  "Operating System :: Unix",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Scientific/Engineering :: Astronomy",
]
dependencies = [
  "numpy",
]
description = "A minimal implementation of the IQRM interference flagging algorithm"
license = "MIT"
license-files = ["LICENSE"]
name = "iqrm"
readme = "README.md"
requires-python = ">=3.10"

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-cov>=6.0",
    "ruff>=0.14.0",
]

[project.urls]
Documentation = "https://github.com/v-morello/iqrm"
Homepage = "https://github.com/v-morello/iqrm"
Issues = "https://github.com/v-morello/iqrm/issues"
Source = "https://github.com/v-morello/iqrm"

[tool.setuptools]
include-package-data = true
packages = {find = {where = ["src"]}}
zip-safe = false

[tool.pytest]
addopts = ["-vv"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["D", "E", "W", "F", "B", "I", "PL"]
ignore = [
    "D100", # Missing docstring in public module
    "D104", # Missing docstring in public package
    "D203",  # incorrect-blank-line-before-class
    "D213",  # multi-line-summary-second-line
]